server:
  port: 8090

spring:
  data:
    mongodb:
      username: cubixroot
      password: cubixroot
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin